version: "3.8"
services:
  intelligence:
    image: ai-delver-intelligence:standalone
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE_VAR}
    ports:
      - "8001:8001"
    restart: unless-stopped